class Idioma:

    ATUAL = "pt"

    TEXTOS = {
        "pt": {

            # Comuns a várias telas
            "comum.id": "ID",
            "comum.nome": "Nome",
            "comum.novo": "Novo",
            "comum.salvar": "Salvar",
            "comum.alterar": "Alterar",
            "comum.excluir": "Excluir",
            "comum.fechar": "Fechar",
            "comum.cancelar": "Cancelar",
            "comum.confirmacao": "Confirmação",
            "comum.erro_prefixo": "Erro: ",

            # Tela de Estados
            "estado.janela_titulo": "CRUD de Estados",
            "estado.titulo": "Cadastro de Estados",
            "estado.dados_frame": "Dados do estado",
            "estado.nome": "Nome:",
            "estado.sigla": "Sigla",
            "estado.confirmar_exclusao": "Deseja realmente excluir este estado?",
            "estado.cadastrado_sucesso": "Estado cadastrado com sucesso!",
            "estado.atualizado_sucesso": "Estado atualizado com sucesso!",
            "estado.excluido_sucesso": "Estado excluído com sucesso!",
            "estado.nao_encontrado": "Estado não encontrado.",
            "estado.selecione_da_lista": "Selecione um estado na lista.",
            "estado.erro_ao_excluir": "Problemas ao excluir estado",
            "estado.erro_sigla_tamanho": "A sigla deve possuir exatamente 2 caracteres.",

            # Tela de Cidades
            "cidade.janela_titulo": "CRUD de Cidades",
            "cidade.titulo": "Cadastro de Cidades",
            "cidade.dados_frame": "Dados de cidade",
            "cidade.id": "ID",
            "cidade.nome": "Nome",
            "cidade.estado": "Estado",
            "cidade.confirmacao": "Deseja realmente excluir esta cidade?",
            "cidade.dados_cidade": "Selecione um estado.",
            "cidade.cadastrado_sucesso": "Cidade cadastrada com sucesso!",
            "cidade.selecionar_cidade": "Selecione uma cidade na lista.",
            "cidade.cidade_atualizada": "Cidade atualizada com sucesso!",
            "cidade.selecione_da_lista": "Selecione uma cidade na lista. ",
            "cidade.cidade_excluida": "Cidade excluída com sucesso!",
            "cidade.cidade_nao_encontrada": "Cidade não encontrada.",
            "cidade.problema_excluir": "Problemas ao excluir cidade",

            # Tela de Fornecedores
            "fornecedor.janela_titulo": "CRUD de Fornecedor",
            "fornecedor.titulo": "Cadastro de Fornecedores",
            "fornecedor.dados_frame": "Dados de fornecedor",
            "fornecedor.id": "ID",
            "fornecedor.razao_social": "Razao social:",
            "fornecedor.nome_fantasia": "Nome fantasia:",
            "fornecedor.cnpj": "CNPJ:",
            "fornecedor.categoria": "Categoria",
            "fornecedor.sla_de_atendimento": "SLA de atendimento:",
            "fornecedor.confirmação": "Deseja realmente excluir este fornecedor?",
            "fornecedor.validar_sla": "O SLA de atendimento não pode ser negativo.",
            "fornecedor.fornecedor_cadastrado": "Fornecedor cadastrado com sucesso!",
            "fornecedor.erro_de_entrada": "Erro: Entrada inválida. Tente novamente.",
            "fornecedor.selecionar_fornecedor": "Selecione um fornecedor na lista.",
            "fornecedor.fornecedor_atualizado": "Fornecedor atualizado com sucesso!",
            "fornecedor.exluido": "Fornecedor excluído com sucesso!",
            "fornecedor.nao_encontrado": "Fornecedor não encontrado.",
            "fornecedor.problema_excluir":"Problemas ao excluir fornecedor.",
            "fornecedor.categorias": "Cadastre categorias antes de associá-las a um fornecedor.",
            "fornecedor.categorias_atualizadas": "Categorias do fornecedor atualizadas com sucesso!",
            "fornecedor.categorias_nao_salvas": "Não foi possivel salvar as categorias do fornecedor.",

            # Tela de Produto
            "produto.janela_titulo": "CRUD DE Produtos",
            "produto.titulo": "Cadastro de Produtos",
            "produto.dados_frame": "Dados do produto",
            "produto.id": "ID",
            "produto.nome": "Nome:",
            "produto.fornecedor": "Fornecedor:",
            "produto.estoque": "Estoque:",
            "produto.preco": "Preço: ",
            "produto.confirmação": "Deseja realmente excluir este produto?",
            "produto.selecionar_fornecedor": "Selecione um fornecedor.",
            "produto.preco_negativo": "O preço não pode ser negativo.",
            "produto.estoque_negativo": "O estoque não pode ser negativo.",
            "produto.cadastrado": "Produto cadastrado com sucesso!",
            "produto.selecionar_produto": "Selecione um produto na lista",
            "produto.atualizar": "Produto atualizado com sucesso!",
            "produto.excluir": "Produto excluído com sucesso!",
            "produto.nao_encontrado": "Produto não encontrado",
            "produto.problema_excluir": "Problemas ao excluir produto.",

            #Tela Usuario
            "usuario.janela_titulo": "CRUD DE Usuario",
            "usuario.titulo": "Cadastro de Usuario",
            "usuario.dados_frame": "Dados do usuario",
            "usuario.id": "ID",
            "usario.nome": "Nome:",
            "usuario.email": "Email:",
            "usuario.nascimento": "Nascimento",
            "usuario.estado": "Estado: ",
            "usuario.cidade": "Cidade:",
            "usuario.perfis": "Perfis:",
            "usuario.confirmação": "Deseja realmente excluir este usuario?",
            "usuario.nascimento_invalido": "Data de nascimento invalida. use o formato DD/MM/AAAA.",
            "usuario.selecione_cidade": "Selecione uma cidade.",
            "usuario.selecione_perfil": "Selecione um perfil.",
            "usuario.cadastrado": "Usuario cadastrado com sucesso!",
            "usuario.selecione_usuario": "Selecione um usuairo na lista",
            "usuario.atualizado": "Usuario atualizado com sucesso!",
            "usuario.excluido": "Usuario excluido com sucesso!",
            "usuario.nao_encontrado": "Usuario não encontrado.",
            "usuario.problemas_excluir": "Problemas ao excluir usuario.",

            #Tela Perfis
            "perfis.janela_titulo": "Crud de Perfis",
            "perfis.titulo": "Cadastro de Perfis",
            "perfis.dados_frame": "Dados do perfil",
            "perfis.id": "ID:",
            "perfis.nome": "Nome:",
            "perfis.descricao": "Descricao",
            "perfis.fornecedores": "Fornecedores",
            "perfis.confirmacao": "Deseja realmente excluir este perfil?",
            "perfis.cadastrado": "Perfil cadastrado com sucesso",
            "perfis.erro": "Erro: entrada invalida. tente novamente",
            "perfis.selecionar_lista": "Selecione um perfil na lista",
            "perfis.atualizado": "Perfil atualizado com sucesso!",
            "perfis.excluido": "Perfil excluido com sucesso!",
            "perfis.nao_encontrado": "Perfil não encontrado",
            "perfis.problemas_excluir": "Problemas ao excluir perfil",

            #Tela de Cliente
            "cliente.janela_titulo": "Crud de Cliente",
            "cliente.titulo": "Cadastro de Clientes",
            "cliente.dados_frame": "Dados do cliente",
            "cliente.id": "ID:",
            "cliente.nome": "Nome:",
            "cliente.nascimento": "Nacimento (DD/MM/AAAA):",
            "cliente.limite_credito": "Limite de crédito: ",
            "cliente.estado": "Estado:",
            "cliente.cidade": "Cidade:",
            "cliente.confirmacao": "Deseja realmente excluir este cliente?",
            "cliente.nascimento_invalido": "Data de nascimento inválida. Use o formato DD/MM/AAAA",
            "cliente.selecionar_cidade": "Selecione uma cidade: ",
            "cliente.limite_negatico": "O limite não pode ser negativo",
            "cliente.cadastrado": "Cliente cadastrado com sucesso!",
            "cliente.selecione_na_lista": "Selecione um cliente na lista",
            "cliente.atualizado": "Cliente atualizado com sucesso",
            "cliente.excluido": "Cliente excluido com sucesso",
            "cliente.problema_excluir": "Problemas ao excluir cliente",
            "cliente.nao_encontrado" : "Cliente não encontrado",

            #Tela de Categoria
            "categoria.janela_titulo": "Crud de Categorias",
            "categoria.titulo": "Cadastro de Categorias",
            "categoria.daods_frame": "Dados da categoria",
            "categoria.id": "ID",
            "categoria.nome": "Nome: ",
            "categoria.confirmacao": "Deseja realmente excluir esta categoria?",
            "categoria.cadastrada": "Categoria cadastrada com sucesso!",
            "categoria.selecione_categoria": "Selecione um categoria na lista",
            "categoria.atualizada": "Categoria atualizada com sucesso!",
            "categoria.selecione_lista": "Selecione uma categoria na lista",
            "categoria.excluida": "Categoria excluída com sucesso!",
            "categoria.nao_encontrada": "Categoria não encontrada.",
            "categoria.problema_excluir": "Problemas ao excluir categoria",










            # Menu principal
            "menu.cadastros_basicos": "Cadastros básicos",
            "menu.estados": "Estados",
            "menu.cidades": "Cidades",
            "menu.acessos": "Acessos",
            "menu.usuarios": "Usuários",
            "menu.perfis": "Perfis",
            "menu.gestao_estoque": "Gestão de estoque",
            "menu.clientes": "Clientes",
            "menu.fornecedores": "Fornecedores",
            "menu.produtos": "Produtos",
            "menu.categorias": "Categorias",
            "menu.idioma": "Idioma",
            "menu.sair": "Sair",
        },
        "en": {

            # Common to several screens
            "comum.id": "ID",
            "comum.nome": "Name",
            "comum.novo": "New",
            "comum.salvar": "Save",
            "comum.alterar": "Edit",
            "comum.excluir": "Delete",
            "comum.fechar": "Close",
            "comum.cancelar": "Cancel",
            "comum.confirmacao": "Confirmation",
            "comum.erro_prefixo": "Error: ",

            # States screen
            "estado.janela_titulo": "State Management",
            "estado.titulo": "State Registration",
            "estado.dados_frame": "State data",
            "estado.nome": "Name:",
            "estado.sigla": "Abbreviation",
            "estado.confirmar_exclusao": "Do you really want to delete this state?",
            "estado.cadastrado_sucesso": "State registered successfully!",
            "estado.atualizado_sucesso": "State updated successfully!",
            "estado.excluido_sucesso": "State deleted successfully!",
            "estado.nao_encontrado": "State not found.",
            "estado.selecione_da_lista": "Select a state from the list.",
            "estado.erro_ao_excluir": "Problem deleting state",
            "estado.erro_sigla_tamanho": "The abbreviation must have exactly 2 characters.",

            # Cities screen
            "cidade.janela_titulo": "City management",
            "cidade.titulo": "City registration",
            "cidade.dados_frame": "City data",
            "cidade.id": "ID",
            "cidade.nome": "Name",
            "cidade.estado": "State",
            "cidade.confirmacao": "Do you really want to delete this City?",
            "cidade.dados_cidade": "Select a city .",
            "cidade.cadastrado_sucesso": "City registered successfully!!",
            "cidade.selecionar_cidade": "Select a city on the list",
            "cidade.cidade_atualizada": "City updated successfully!",
            "cidade.selecione_da_lista": "Select a city on the list. ",
            "cidade.cidade_excluida": "City deleted successfully!",
            "cidade.cidade_nao_encontrada": "City not found.",
            "cidade.problema_excluir": "Problem deleting City",

            
            # suppliers screen
            "fornecedor.janela_titulo": "Suppliers management",
            "fornecedor.titulo": "suppliers registration",
            "fornecedor.dados_frame": "Suppliers data",
            "fornecedor.id": "ID",
            "fornecedor.razao_social": "Company name:",
            "fornecedor.nome_fantasia": "Trade name:",
            "fornecedor.cnpj": "CNPJ:",
            "fornecedor.categoria": "Category:",
            "fornecedor.sla_de_atendimento": "Service response SLA:",
            "fornecedor.confirmação": "Do you really want to delete this Supplier?",
            "fornecedor.validar_sla": "The service response SLA can't be negativ.",
            "fornecedor.fornecedor_cadastrado": "Supplier registered successfully!",
            "fornecedor.erro_de_entrada": "Error: Invalid input. Try again.",
            "fornecedor.selecionar_fornecedor": "Select a supplier on the list",
            "fornecedor.fornecedor_atualizado": "Supplier updated successfully!",
            "fornecedor.exluido": "Supplier deleted successfully!",
            "fornecedor.nao_encontrado": "Supplier not found.",
            "fornecedor.problema_excluir":"Problem deleting supplier.",
            "fornecedor.categorias": "Register categories before linking them to a supplier.",
            "fornecedor.categorias_atualizadas": "Supplier categories updated successfully!",
            "fornecedor.categorias_nao_salvas": "It wasn't possible to save the supplier's categories.",

            # Product screen
            "produto.janela_titulo": "Product management",
            "produto.titulo": "Product registration",
            "produto.dados_frame": "Product data",
            "produto.id": "ID",
            "produto.nome": "Name:",
            "produto.fornecedor": "Supplier:",
            "produto.estoque": "Stock:",
            "produto.preco": "Price: ",
            "produto.confirmação": "Do you really want to delete this Product?",
            "produto.selecionar_fornecedor": "Select a Product.",
            "produto.preco_negativo": "The price can't be negativ.",
            "produto.estoque_negativo": "The stock can't be negativ.",
            "produto.cadastrado": "Product registered successfully!!",
            "produto.selecionar_produto": "Select a product on the list",
            "produto.atualizar": "Product updated successfully!",
            "produto.excluir": "Product deleted successfully",
            "produto.nao_encontrado": "Product not found",
            "produto.problema_excluir": "Problema deleting product",

            #Users screen
            "usuario.janela_titulo": "Users management",
            "usuario.titulo": "Users registration",
            "usuario.dados_frame": "Users data",
            "usuario.id": "ID",
            "usario.nome": "Name:",
            "usuario.email": "Email:",
            "usuario.nascimento": "Birth",
            "usuario.estado": "Supplier: ",
            "usuario.cidade": "City:",
            "usuario.perfis": "Profiles:",
            "usuario.confirmação": "Do you really want to delete this User?",
            "usuario.nascimento_invalido": "Invalid birth date. Use the format DD/MM/YYYY.",
            "usuario.selecione_cidade": "Select a city.",
            "usuario.selecione_perfil": "Select a profile.",
            "usuario.cadastrado": "User registered successfully!",
            "usuario.selecione_usuario": "Select an user on the list",
            "usuario.atualizado": "User updated successfully!",
            "usuario.excluido": "User deleted successfully!",
            "usuario.nao_encontrado": "User not found",
            "usuario.problemas_excluir": "Problem deleting user.",

            #Profiles screen
            "perfis.janela_titulo": "Profiles management",
            "perfis.titulo": "Profiles registration",
            "perfis.dados_frame": "Profiles data",
            "perfis.id": "ID:",
            "perfis.nome": "Name:",
            "perfis.descricao": "Description",
            "perfis.fornecedores": "Suppliers",
            "perfis.confirmacao": "Do you really want to delete this Profile?",
            "perfis.cadastrado": "Profile registered successfully!",
            "perfis.erro": "Error: invalid input. please try again",
            "perfis.selecionar_lista": "Select a profile on the list",
            "perfis.atualizado": "Profile updated successfully!",
            "perfis.excluido": "Profile deleted successfully!",
            "perfis.nao_encontrado": "Profile not found",
            "perfis.problemas_excluir": "Problem deleting profile",

            #Client screen
            "cliente.janela_titulo": "Client management",
            "cliente.titulo": "Client registration",
            "cliente.dados_frame": "Client data",
            "cliente.id": "ID:",
            "cliente.nome": "Name:",
            "cliente.nascimento": "birth (DD/MM/YYYY):",
            "cliente.limite_credito": "Limite de crédito: ",
            "cliente.estado": "State:",
            "cliente.cidade": "City:",
            "cliente.confirmacao": "Do you really want to delete this Client?",
            "cliente.nascimento_invalido": "Invalid birth date. Use the format DD/MM/YYYY",
            "cliente.selecionar_cidade": "Select a city: ",
            "cliente.limite_negatico": "The limit can't be negativ",
            "cliente.cadastrado": "Client registered successfully!",
            "cliente.selecione_na_lista": "Select a client on the list",
            "cliente.atualizado": "Client updated successfully!",
            "cliente.excluido": "Client deleted successfully!",
            "cliente.problema_excluir": "Problem deleting client",
            "cliente.nao_encontrado" : "Client not found",

            #Category screen
            "categoria.janela_titulo": "Category management",
            "categoria.titulo": "Category registration",
            "categoria.daods_frame": "Category data",
            "categoria.id": "ID",
            "categoria.nome": "Name: ",
            "categoria.confirmacao": "Do you really want to delete this Category?",
            "categoria.cadastrada": "Category registered successfully!",
            "categoria.selecione_categoria": "Select a category on the list",
            "categoria.atualizada": "Category updated successfully!",
            "categoria.selecione_lista": "Select a category on the list",
            "categoria.excluida": "Category deleted successfully!",
            "categoria.nao_encontrada": "Category not found.",
            "categoria.problema_excluir": "Problem deleting category",

            # Main menu
            "menu.cadastros_basicos": "Basic registrations",
            "menu.estados": "States",
            "menu.cidades": "Cities",
            "menu.acessos": "Access",
            "menu.usuarios": "Users",
            "menu.perfis": "Roles",
            "menu.gestao_estoque": "Inventory management",
            "menu.clientes": "Customers",
            "menu.fornecedores": "Suppliers",
            "menu.produtos": "Products",
            "menu.categorias": "Categories",
            "menu.idioma": "Language",
            "menu.sair": "Exit",
        }
    }

    @classmethod
    def definir(cls, codigo):
        cls.ATUAL = codigo

    @classmethod #usa quando voce tem algum atributo
    #dentro da classe e quer modificar ou acessar esses atributos

    def t(cls, chave): #cls e como se fosse um self porem ele aponta pra classe
        #em vez do objeto
        return cls.TEXTOS[cls.ATUAL].get(chave, chave)
